### ISSUE TITLE
elSOL Price Data Not Updating

### ISSUE THREAD

**Issue by KishiTheMechanic** [glitchful-dev/sol-stake-pool-apy#26]
Hi team,

I’ve noticed that the elSOL price data has stopped updating. 
Could you please check this issue when you have the chance?

https://github.com/glitchful-dev/sol-stake-pool-apy/blob/master/db/elSOL.csv

Alternatively, if there’s a way for me to address this, I’d be happy to submit a pull request to help resolve it.

Thank you as always for the amazing product!

Have a great day!

**Comment by AlexStefan** [comment]
@KishiTheMechanic I've created a PR to address this. The reason of this issue was that we were tracking all the pools with total stake higher than 1k SOL.
Sadly I don't have an easy way/too much time atm to look into how to fill the historical data for the missed epochs. If you have something around this, please create a PR or provide me with the values, and will update the list.

**Comment by janlegner** [comment]
I do not think that for the purposes of the SDK the past data is needed; However, if the intent is to make some plots using this data, backfill would come in handy. What might make sense is to make a PR with linearly extrapolated data between the currently known epoch and the past epoch before that.

**Comment by KishiTheMechanic** [comment]
@AlexStefan Thank you for addressing this! Your help is greatly appreciated. 🙏

@janlegner Thank you! I'll create a PR with the linearly interpolated data, so please bear with me for a bit. 🙏
